default_platform(:mac)

platform :mac do

  before_all do
    @api_key = app_store_connect_api_key(
      key_id: "C5TM86N9PG",
      issuer_id: "a5c4390d-c45c-4453-a560-d6234fcd501e",
      key_filepath: "./fastlane/keys/AuthKey_C5TM86N9PG.p8",
      in_house: false
    )
  end

  desc "Upload metadata to App Store Connect (no binary)"
  lane :metadata do
    deliver(
      api_key: @api_key,
      skip_binary_upload: true,
      skip_screenshots: true,
      force: true
    )
  end

  desc "Upload screenshots to App Store Connect"
  lane :screenshots do
    deliver(
      api_key: @api_key,
      skip_binary_upload: true,
      skip_metadata: true,
      force: true
    )
  end

  desc "Upload metadata + screenshots"
  lane :upload_all do
    deliver(
      api_key: @api_key,
      skip_binary_upload: true,
      force: true
    )
  end

  desc "Submit for App Store review"
  lane :submit do
    deliver(
      api_key: @api_key,
      submit_for_review: true,
      automatic_release: false,
      force: true
    )
  end

end
