# SwiftLint Configuration for AwakeApp
# CI enforces --strict mode (warnings become errors)

disabled_rules:
  - trailing_whitespace
  - line_length
  - todo  # Allow TODO comments during development
  - multiple_closures_with_trailing_closure  # Common SwiftUI pattern
  - large_tuple  # Acceptable in tests for test case data

opt_in_rules:
  - implicitly_unwrapped_optional
  - empty_count
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_string
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - legacy_multiple
  - modifier_order
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - yoda_condition

excluded:
  - build
  - .build
  - DerivedData
  - "*.generated.swift"

# Severity levels for critical rules (blocking in CI)
force_cast: error
force_try: error

# Note: force_unwrapping opt-in rule removed - too noisy in tests
# Production code should prefer safe unwrapping patterns

# Identifier naming
identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - x
    - y
    - i
    - j
    - to
    - up
    - URL

# Type complexity limits (relaxed for SwiftUI views)
type_body_length:
  warning: 500
  error: 800

file_length:
  warning: 850  # Relaxed slightly for complex SwiftUI views
  error: 1200

function_body_length:
  warning: 60  # Relaxed for data-heavy functions (e.g., key code mappings)
  error: 100

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level: 2
  function_level: 3

# Output format
reporter: "xcode"
